=== MageTest/magento/src/app/code/Magento/Sales/etc/sales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="section" type="sectionDeclaration">
                    <xs:unique name="uniqueGroupName">
                        <xs:annotation>
                            <xs:documentation>
                                Group name must be unique.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="group"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="order" type="orderDeclaration">
                    <xs:unique name="uniqueProductTypeName">
                        <xs:annotation>
                            <xs:documentation>
                                Product type name must be unique.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="available_product_type"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="uniqueSectionName">
            <xs:annotation>
                <xs:documentation>
                    Section name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="section"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="sectionDeclaration">
        <xs:annotation>
            <xs:documentation>
                Section declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="group" type="groupDeclaration" minOccurs="0" maxOccurs="unbounded">
                <xs:unique name="uniqueItemName">
                    <xs:annotation>
                        <xs:documentation>
                            Item name must be unique.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath="item"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="groupDeclaration">
        <xs:annotation>
            <xs:documentation>
                Group declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="item" type="itemDeclaration" minOccurs="0" maxOccurs="unbounded">
                <xs:unique name="uniqueRendererName">
                    <xs:annotation>
                        <xs:documentation>
                            Rendeder name must be unique.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath="renderer"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="itemDeclaration">
        <xs:annotation>
            <xs:documentation>
                Item declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="renderer" type="rendererDeclaration" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="instance" type="xs:string" use="optional"/>
        <xs:attribute name="sort_order" type="xs:integer" use="optional"/>
    </xs:complexType>

    <xs:complexType name="rendererDeclaration">
        <xs:annotation>
            <xs:documentation>
                Renderer declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="instance" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="orderDeclaration">
        <xs:annotation>
            <xs:documentation>
                Order declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="available_product_type" type="availableProductTypeDeclaration" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="availableProductTypeDeclaration">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== MageTest/magento/src/app/code/Magento/Tax/etc/sales.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Sales/etc/sales.xsd">
    <section name="quote">
        <group name="totals">
            <item name="tax_subtotal" instance="Magento\Tax\Model\Sales\Total\Quote\Subtotal" sort_order="200"/>
            <item name="tax_shipping" instance="Magento\Tax\Model\Sales\Total\Quote\Shipping" sort_order="300"/>
            <item name="tax" instance="Magento\Tax\Model\Sales\Total\Quote\Tax" sort_order="450">
                <renderer name="adminhtml" instance="Magento\Sales\Block\Adminhtml\Order\Create\Totals\Tax"/>
                <renderer name="frontend" instance="Magento\Tax\Block\Checkout\Tax"/>
            </item>
            <item name="subtotal">
                <renderer name="adminhtml" instance="Magento\Sales\Block\Adminhtml\Order\Create\Totals\Subtotal"/>
                <renderer name="frontend" instance="Magento\Tax\Block\Checkout\Subtotal"/>
            </item>
            <item name="shipping">
                <renderer name="adminhtml" instance="Magento\Sales\Block\Adminhtml\Order\Create\Totals\Shipping"/>
                <renderer name="frontend" instance="Magento\Tax\Block\Checkout\Shipping"/>
            </item>
            <item name="discount">
                <renderer name="adminhtml" instance="Magento\Sales\Block\Adminhtml\Order\Create\Totals\Discount"/>
                <renderer name="frontend" instance="Magento\Tax\Block\Checkout\Discount"/>
            </item>
            <item name="grand_total">
                <renderer name="adminhtml" instance="Magento\Sales\Block\Adminhtml\Order\Create\Totals\Grandtotal"/>
                <renderer name="frontend" instance="Magento\Tax\Block\Checkout\Grandtotal"/>
            </item>
        </group>
        <group name="nominal_totals">
            <item name="nominal_tax_subtotal" instance="Magento\Tax\Model\Sales\Total\Quote\Nominal\Subtotal" sort_order="500"/>
            <item name="nominal_tax" instance="Magento\Tax\Model\Sales\Total\Quote\Nominal\Tax" sort_order="750"/>
        </group>
    </section>
</config>
