=== MageTest/magento/src/app/code/Magento/ImportExport/etc/export.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="entity" type="entityDeclaration" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="entityType" type="entityTypeDeclaration" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="fileFormat" type="fileFormatDeclaration" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
        <xs:unique name="uniqueEntityName">
            <xs:annotation>
                <xs:documentation>
                    Export entity name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="entity"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="uniqueFileFormatName">
            <xs:annotation>
                <xs:documentation>
                    Export file format name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="fileFormat" />
            <xs:field xpath="@name" />
        </xs:unique>
    </xs:element>

    <xs:complexType name="entityDeclaration">
        <xs:annotation>
            <xs:documentation>
                Export entity declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="label" type="xs:string" use="optional" />
        <xs:attribute name="model" type="modelName" use="optional" />
        <xs:attribute name="entityAttributeFilterType" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="entityTypeDeclaration">
        <xs:annotation>
            <xs:documentation>
                Export entity type declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="entity" type="xs:string" use="required" />
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="model" type="modelName" use="required" />
    </xs:complexType>

    <xs:complexType name="fileFormatDeclaration">
        <xs:annotation>
            <xs:documentation>
                Export file format declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="label" type="xs:string" use="optional" />
        <xs:attribute name="model" type="modelName" use="optional" />
    </xs:complexType>

    <xs:simpleType name="modelName">
        <xs:annotation>
            <xs:documentation>
                Model name can contain only [A-Za-z_\\\\].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_\\\\]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MageTest/magento/src/dev/tests/unit/testsuite/Magento/ImportExport/Model/Export/Config/_files/export.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../../app/code/Magento/ImportExport/etc/export.xsd">
    <entity name="product" label="Label_One" model="Model_One" entityAttributeFilterType="product"/>
    <entity name="customer" label="Label_One" model="Model_One" entityAttributeFilterType="customer"/>
    <entityType entity="customer" name="type_one" model="Model_Type_One" />
    <entityType entity="customer" name="type_two" model="Model_Type_Two" />
    <entityType entity="product" name="product_type_one" model="Product_Model_Type_One" />
    <entityType entity="product" name="type_two" model="Model_Type_Two" />
    <fileFormat name="name_three" label="Label_Three" model="Model_Three" />
</config>
