=== MageTest/magento/src/lib/internal/Magento/Framework/Object/etc/fieldset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                Specifies a configuration.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="scope" type="scopeType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="scopeType">
        <xs:annotation>
            <xs:documentation>
                The definition of the current scope.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="fieldset" type="fieldsetType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="fieldsetType">
        <xs:annotation>
            <xs:documentation>
                The set of fields which will be used to filter existing Magento Object data
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="field" type="fieldType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="fieldType">
        <xs:annotation>
            <xs:documentation>
                The name of a field used to extract data from an existing Magento Object
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="aspect" type="aspectType"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:token" use="required"/>
    </xs:complexType>

    <xs:complexType name="aspectType">
        <xs:annotation>
            <xs:documentation>
                The name of an aspect associated with a field. If the targetField is populated, the field data will be
                provided under the name specified by targetField.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:token" use="required"/>
        <xs:attribute name="targetField" type="xs:token" use="optional"/>
    </xs:complexType>

</xs:schema>

=== MageTest/magento/src/app/code/Magento/Customer/etc/fieldset.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Object/etc/fieldset.xsd">
    <scope id="global">
        <fieldset id="customer_account">
            <field name="prefix">
                <aspect name="create" />
                <aspect name="update" />
                <aspect name="name" />
            </field>
            <field name="firstname">
                <aspect name="create" />
                <aspect name="update" />
                <aspect name="name" />
            </field>
            <field name="middlename">
                <aspect name="create" />
                <aspect name="update" />
                <aspect name="name" />
            </field>
            <field name="lastname">
                <aspect name="create" />
                <aspect name="update" />
                <aspect name="name" />
            </field>
            <field name="suffix">
                <aspect name="create" />
                <aspect name="update" />
                <aspect name="name" />
            </field>
            <field name="email">
                <aspect name="create" />
                <aspect name="update" />
            </field>
            <field name="password">
                <aspect name="create" />
            </field>
            <field name="confirmation">
                <aspect name="create" />
            </field>
            <field name="dob">
                <aspect name="create" />
                <aspect name="update" />
            </field>
            <field name="taxvat">
                <aspect name="create" />
                <aspect name="update" />
            </field>
            <field name="gender">
                <aspect name="create" />
                <aspect name="update" />
            </field>
        </fieldset>
        <fieldset id="customer_address">
            <field name="vat_id">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_is_valid">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_request_id">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_request_date">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_request_success">
                <aspect name="to_quote_address" />
            </field>
        </fieldset>
        <fieldset id="sales_convert_order_address">
            <field name="vat_id">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_is_valid">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_request_id">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_request_date">
                <aspect name="to_quote_address" />
            </field>
            <field name="vat_request_success">
                <aspect name="to_quote_address" />
            </field>
        </fieldset>
        <fieldset id="sales_convert_quote_address">
            <field name="vat_id">
                <aspect name="to_order_address" />
                <aspect name="to_customer_address" />
            </field>
            <field name="vat_is_valid">
                <aspect name="to_order_address" />
                <aspect name="to_customer_address" />
            </field>
            <field name="vat_request_id">
                <aspect name="to_order_address" />
                <aspect name="to_customer_address" />
            </field>
            <field name="vat_request_date">
                <aspect name="to_order_address" />
                <aspect name="to_customer_address" />
            </field>
            <field name="vat_request_success">
                <aspect name="to_order_address" />
                <aspect name="to_customer_address" />
            </field>
        </fieldset>
        <fieldset id="sales_copy_order_billing_address">
            <field name="vat_id">
                <aspect name="to_order" />
            </field>
            <field name="vat_is_valid">
                <aspect name="to_order" />
            </field>
            <field name="vat_request_id">
                <aspect name="to_order" />
            </field>
            <field name="vat_request_date">
                <aspect name="to_order" />
            </field>
            <field name="vat_request_success">
                <aspect name="to_order" />
            </field>
        </fieldset>
    </scope>
</config>
