=== MageTest/magento/src/lib/internal/Magento/Framework/Event/etc/events.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" type="eventDeclaration" minOccurs="1" maxOccurs="unbounded">
                    <xs:unique name="uniqueObserverName">
                        <xs:annotation>
                            <xs:documentation>
                                Observer name must be unique.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="observer"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueEventName">
            <xs:annotation>
                <xs:documentation>
                    Event name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="event" />
            <xs:field xpath="@name" />
        </xs:unique>
    </xs:element>

    <xs:complexType name="eventDeclaration">
        <xs:annotation>
            <xs:documentation>
                Event declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="observer" type="observerDeclaration" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="eventName" use="required" />
    </xs:complexType>

    <xs:complexType name="observerDeclaration">
        <xs:annotation>
            <xs:documentation>
                Observer declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="instance" type="xs:string" use="optional" />
        <xs:attribute name="method" type="methodName" use="optional" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
        <xs:attribute name="shared" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:simpleType name="methodName">
        <xs:annotation>
            <xs:documentation>
                Method name can contain only English letters.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="eventName">
        <xs:annotation>
            <xs:documentation>
                Event name can contain only [a-zA-Z_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MageTest/magento/src/app/code/Magento/Downloadable/etc/frontend/events.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/Event/etc/events.xsd">
    <event name="sales_order_item_save_commit_after">
        <observer name="downloadable_observer" instance="Magento\Downloadable\Model\Observer" method="saveDownloadableOrderItem" />
    </event>
    <event name="sales_order_save_commit_after">
        <observer name="downloadable_observer" instance="Magento\Downloadable\Model\Observer" method="setLinkStatus" />
    </event>
    <event name="checkout_type_onepage_save_order_after">
        <observer name="checkout_type_onepage_save_order_after" instance="Magento\Downloadable\Model\Observer" method="setHasDownloadableProducts" />
    </event>
    <event name="checkout_type_multishipping_create_orders_single">
        <observer name="checkout_type_multishipping_create_orders_single" instance="Magento\Downloadable\Model\Observer" method="setHasDownloadableProducts" />
    </event>
    <event name="checkout_allow_guest">
        <observer name="checkout_allow_guest" instance="Magento\Downloadable\Model\Observer" method="isAllowedGuestCheckout" />
    </event>
    <event name="product_option_renderer_init">
        <observer name="downloadable_observer" instance="Magento\Downloadable\Model\Observer" method="initOptionRenderer" />
    </event>
</config>

=== MageTest/magento/src/app/code/Magento/Sales/etc/adminhtml/events.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/Event/etc/events.xsd">
    <event name="catalog_product_delete_before">
        <observer name="sales_quote_observer" instance="Magento\Sales\Model\Observer\Backend\CatalogProductQuote" method="subtractQtyFromQuotes" />
    </event>
    <event name="catalogrule_before_apply">
        <observer name="sales_quote_observer" instance="Magento\Sales\Model\Observer\Backend\CatalogPriceRule" method="dispatch" />
    </event>
    <event name="catalogrule_after_apply">
        <observer name="sales_quote_observer" instance="Magento\Sales\Model\Observer\Backend\CatalogPriceRule" method="dispatch" />
    </event>
    <event name="catalog_product_save_after">
        <observer name="sales_quote" instance="Magento\Sales\Model\Observer\Backend\CatalogProductQuote" method="catalogProductSaveAfter" />
    </event>
    <event name="catalog_product_status_update">
        <observer name="sales_quote" instance="Magento\Sales\Model\Observer\Backend\CatalogProductQuote" method="catalogProductStatusUpdate" />
    </event>
    <event name="customer_save_after_data_object">
        <observer name="customer" instance="Magento\Sales\Model\Observer\Backend\CustomerQuote" method="dispatch" />
    </event>
</config>

=== MageTest/magento/src/app/code/Magento/CatalogInventory/etc/events.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Event/etc/events.xsd">
    <event name="catalog_block_product_status_display">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="displayProductStatusInfo" />
    </event>
    <event name="catalog_product_load_after">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="addInventoryData" />
    </event>
    <event name="catalog_product_collection_load_after">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="addStockStatusToCollection" />
    </event>
    <event name="sales_quote_item_collection_products_after_load">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="addInventoryDataToCollection" />
    </event>
    <event name="sales_quote_item_qty_set_after">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Quote\Item\QuantityValidator" method="validate" />
    </event>
    <event name="checkout_submit_all_after">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="checkoutAllSubmitAfter" />
    </event>
    <event name="sales_model_service_quote_submit_before">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="subtractQuoteInventory" />
    </event>
    <event name="sales_model_service_quote_submit_success">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="reindexQuoteInventory" />
    </event>
    <event name="sales_model_service_quote_submit_failure">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="revertQuoteInventory" />
    </event>
    <event name="restore_quote">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="revertQuoteInventory" />
    </event>
    <event name="sales_order_item_cancel">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="cancelOrderItem" />
    </event>
    <event name="sales_order_creditmemo_save_after">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="refundOrderInventory" />
    </event>
    <event name="catalog_product_save_after">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="saveInventoryData" />
    </event>
    <event name="admin_system_config_changed_section_cataloginventory">
        <observer name="inventory" instance="Magento\CatalogInventory\Model\Observer" method="updateItemsStockUponConfigChange" />
    </event>
</config>

=== MageTest/magento/src/app/code/Magento/Persistent/etc/frontend/events.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/Event/etc/events.xsd">
    <event name="customer_data_object_login">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\Session" method="synchronizePersistentOnLogin" />
    </event>
    <event name="customer_logout">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\Session" method="synchronizePersistentOnLogout" />
    </event>
    <event name="controller_front_send_response_after">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\Session" method="synchronizePersistentInfo" />
    </event>
    <event name="controller_action_predispatch_customer_account_loginPost">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\Session" method="setRememberMeCheckedStatus" />
    </event>
    <event name="controller_action_predispatch_customer_account_createpost">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\Session" method="setRememberMeCheckedStatus" />
        <observer name="persistent_authenticate" instance="Magento\Persistent\Model\Observer\CustomerAuthenticatedEvent" method="execute" />
    </event>
    <event name="controller_action_postdispatch_checkout_onepage_saveBilling">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\Session" method="setRememberMeCheckedStatus" />
    </event>
    <event name="controller_action_layout_generate_blocks_after">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\ApplyPersistentData" method="execute" />
    </event>
    <event name="controller_action_predispatch">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\EmulateQuote" method="execute" />
        <observer name="persistent_session" instance="Magento\Persistent\Model\Observer\Session" method="renewCookie" />
        <observer name="persistent_quote" instance="Magento\Persistent\Model\Observer\CheckExpirePersistentQuote" method="execute" />
        <observer name="persistent_customer" instance="Magento\Persistent\Model\Observer\EmulateCustomer" method="execute" />
        <observer name="persistent_checkout" instance="Magento\Persistent\Model\Observer\PreventExpressCheckout" method="execute" />
    </event>
    <event name="checkout_allow_guest">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\DisableGuestCheckout" method="execute" />
    </event>
    <event name="customer_customer_authenticated">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\CustomerAuthenticatedEvent" method="execute" />
    </event>
    <event name="controller_action_predispatch_persistent_index_unsetCookie">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\PreventClearCheckoutSession" method="execute" />
    </event>
    <event name="controller_action_postdispatch_persistent_index_unsetCookie">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\MakePersistentQuoteGuest" method="execute" />
    </event>
    <event name="sales_quote_save_before">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\SetQuotePersistentData" method="execute" />
    </event>
    <event name="custom_quote_process">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\SetLoadPersistentQuote" method="execute" />
    </event>
    <event name="customer_register_success">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\RemovePersistentCookie" method="execute" />
    </event>
    <event name="render_block">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\ApplyBlockPersistentData" method="execute" />
    </event>
    <event name="update_customer_cookies">
        <observer name="persistent" instance="Magento\Persistent\Model\Observer\UpdateCustomerCookies" method="execute" />
    </event>
</config>
