=== MageTest/magento/src/app/code/Magento/Webapi/etc/webapi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Structure description for webapi.xml configuration files.
 *
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="routes" type="routesType"/>

    <xs:complexType name="routesType">
        <xs:sequence>
            <xs:element name="route" type="routeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="routeType">
        <xs:sequence>
            <xs:element name="service" type="serviceType"/>
            <xs:element name="resources" type="resourcesType"/>
            <xs:element name="data" type="dataType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="method" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="GET"/>
                    <xs:enumeration value="PUT"/>
                    <xs:enumeration value="POST"/>
                    <xs:enumeration value="DELETE"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="url" type="xs:string" use="required"/>
        <xs:attribute name="secure" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="serviceType">
        <xs:attribute name="class" type="xs:string" use="required"/>
        <xs:attribute name="method" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="resourcesType" >
        <xs:sequence>
            <xs:element name="resource" type="resourceType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="resourceType">
       <xs:attribute name="ref" use="required">
           <xs:simpleType>
               <xs:restriction base="xs:string">
                   <xs:pattern value=".+(, ?.+)*"/>
               </xs:restriction>
           </xs:simpleType>
       </xs:attribute>
    </xs:complexType>

    <xs:complexType name="dataType" >
        <xs:sequence>
            <xs:element name="parameter" type="parameterType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="force" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== MageTest/magento/src/app/code/Magento/Bundle/etc/webapi.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../app/code/Magento/Webapi/etc/webapi.xsd">
    <route url="/V1/bundle-products/:productSku/links/:optionId" method="POST">
        <service class="Magento\Bundle\Service\V1\Product\Link\WriteServiceInterface" method="addChild"/>
        <resources>
            <resource ref="Magento_Catalog::products"/>
        </resources>
    </route>
    <route url="/V1/bundle-products/:productId/children" method="GET">
        <service class="Magento\Bundle\Service\V1\Product\Link\ReadServiceInterface" method="getChildren"/>
        <resources>
            <resource ref="Magento_Catalog::products"/>
        </resources>
    </route>
    <route url="/V1/bundle-products/:productSku/option/:optionId/child/:childSku" method="DELETE">
        <service class="Magento\Bundle\Service\V1\Product\Link\WriteServiceInterface" method="removeChild"/>
        <resources>
            <resource ref="Magento_Catalog::products"/>
        </resources>
    </route>
    <route url="/V1/bundle-products/:productSku/option/all" method="GET">
        <service class="Magento\Bundle\Service\V1\Product\Option\ReadServiceInterface" method="getList" />
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
    <route url="/V1/bundle-products/option/types" method="GET">
        <service class="Magento\Bundle\Service\V1\Product\Option\Type\ReadServiceInterface" method="getTypes" />
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
    <route url="/V1/bundle-products/:productSku/option/:optionId" method="GET">
        <service class="Magento\Bundle\Service\V1\Product\Option\ReadServiceInterface" method="get" />
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
    <route url="/V1/bundle-products/:productSku/option/add" method="POST">
        <service class="Magento\Bundle\Service\V1\Product\Option\WriteServiceInterface" method="add" />
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
    <route url="/V1/bundle-products/:productSku/option/:optionId" method="PUT">
        <service class="Magento\Bundle\Service\V1\Product\Option\WriteServiceInterface" method="update" />
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
    <route url="/V1/bundle-products/:productSku/option/:optionId" method="DELETE">
        <service class="Magento\Bundle\Service\V1\Product\Option\WriteServiceInterface" method="remove" />
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
</routes>

=== MageTest/magento/src/dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Webapi/Model/_files/webapi.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../../../../../../../app/code/Magento/Webapi/etc/webapi.xsd">
    <route url="/V1/customers/me" method="GET">
        <service class="Magento\Customer\Service\V1\CustomerServiceInterface" method="getCustomer" />
        <resources>
            <resource ref="Magento_Customer::customer_self" />
        </resources>
        <data>
            <parameter name="id" force="true">null</parameter>
        </data>
    </route>
    <route url="/V1/customers/me" method="PUT" secure="true">
        <service class="Magento\Customer\Service\V1\CustomerServiceInterface" method="updateCustomer" />
        <resources>
            <resource ref="Magento_Customer::customer_self" />
        </resources>
        <data>
            <parameter name="id">null</parameter>
        </data>
    </route>
    <route url="/V1/customers" method="POST">
        <service class="Magento\Customer\Service\V1\CustomerServiceInterface" method="createCustomer" />
        <resources>
            <resource ref="Magento_Customer::manage" />
        </resources>
    </route>
    <route url="/V1/customers/:id" method="GET">
        <service class="Magento\Customer\Service\V1\CustomerServiceInterface" method="getCustomer" />
        <resources>
            <resource ref="Magento_Customer::read" />
        </resources>
    </route>
</routes>

=== MageTest/magento/src/dev/tests/integration/testsuite/Magento/Webapi/Model/Config/_files/webapiA.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../../../../../app/code/Magento/Webapi/etc/webapi.xsd">
    <route url="/V1/testmodule1/:id" method="GET">
        <service class="Magento\TestModule1\Service\V1\AllSoapAndRestInterface" method="item"/>
        <resources>
            <resource ref="Magento_Test1::resource1"/>
        </resources>
    </route>
    <route url="/V2/testmodule1/:id" method="GET">
        <service class="Magento\TestModule1\Service\V2\AllSoapAndRestInterface" method="item"/>
        <resources>
            <resource ref="Magento_Test1::resource1"/>
            <resource ref="Magento_Test1::resource2"/>
        </resources>
    </route>
    <route url="/V2/testmodule1" method="POST">
        <service class="Magento\TestModule1\Service\V2\AllSoapAndRestInterface" method="create"/>
        <resources>
            <resource ref="Magento_Test1::resource1"/>
            <resource ref="Magento_Test1::resource2"/>
        </resources>
        <data>
            <parameter name="id" force="true">null</parameter>
        </data>
    </route>
    <route url="/V2/testmodule1/:id" method="DELETE">
        <service class="Magento\TestModule1\Service\V2\AllSoapAndRestInterface" method="delete"/>
        <resources>
            <resource ref="Magento_Test1::resource1"/>
            <resource ref="Magento_Test1::resource2"/>
        </resources>
    </route>
</routes>
