=== MageTest/magento/src/app/code/Magento/Indexer/etc/indexer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="indexer" type="indexerType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueIndexertId">
            <xs:annotation>
                <xs:documentation>
                    Indexer Id must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="indexer" />
            <xs:field xpath="@id" />
            <xs:field xpath="@view_id" />
        </xs:unique>
        <xs:unique name="uniqueViewId">
            <xs:annotation>
                <xs:documentation>
                    Indexer Id must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="indexer" />
            <xs:field xpath="@view_id" />
        </xs:unique>
    </xs:element>

    <xs:complexType name="indexerType">
        <xs:annotation>
            <xs:documentation>
                Indexer declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="title" type="translatableType" />
            <xs:element name="description" type="translatableType" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="view_id" type="viewIdType" use="required" />
        <xs:attribute name="class" type="classType" use="required" />
    </xs:complexType>

    <xs:complexType name="translatableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="translate" use="optional" fixed="true" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="viewIdType">
        <xs:annotation>
            <xs:documentation>
                View ID can contain only [a-zA-Z0-9_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="classType">
        <xs:annotation>
            <xs:documentation>
                Class name can contain only [a-zA-Z\].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z\\]+" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== MageTest/magento/src/app/code/Magento/Catalog/etc/indexer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Indexer/etc/indexer.xsd">
    <indexer id="catalog_product_flat" view_id="catalog_product_flat" class="Magento\Catalog\Model\Indexer\Product\Flat">
        <title translate="true">Product Flat Data</title>
        <description translate="true">Reorganize EAV product structure to flat structure</description>
    </indexer>
    <indexer id="catalog_category_flat" view_id="catalog_category_flat" class="Magento\Catalog\Model\Indexer\Category\Flat">
        <title translate="true">Category Flat Data</title>
        <description translate="true">Reorganize EAV category structure to flat structure</description>
    </indexer>
    <indexer id="catalog_category_product" view_id="catalog_category_product" class="Magento\Catalog\Model\Indexer\Category\Product">
        <title translate="true">Category Products</title>
        <description translate="true">Indexed category/products association</description>
    </indexer>
    <indexer id="catalog_product_category" view_id="catalog_product_category" class="Magento\Catalog\Model\Indexer\Product\Category">
        <title translate="true">Product Categories</title>
        <description translate="true">Indexed product/categories association</description>
    </indexer>
    <indexer id="catalog_product_price" view_id="catalog_product_price" class="Magento\Catalog\Model\Indexer\Product\Price">
        <title translate="true">Product Price</title>
        <description translate="true">Index product prices</description>
    </indexer>
    <indexer id="catalog_product_attribute" view_id="catalog_product_attribute" class="Magento\Catalog\Model\Indexer\Product\Eav">
        <title translate="true">Product EAV</title>
        <description translate="true">Index product EAV</description>
    </indexer>
</config>
