=== MageTest/magento/src/lib/internal/Magento/Framework/Mview/etc/mview.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="view" type="viewType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueViewId">
            <xs:annotation>
                <xs:documentation>
                    View Id must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="view" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>

    <xs:complexType name="viewType">
        <xs:annotation>
            <xs:documentation>
                View declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="subscriptions" type="subscriptionsType">
                <xs:unique name="uniqueSubscriptionsTable">
                    <xs:annotation>
                        <xs:documentation>
                            Table must be unique.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath=".//table" />
                    <xs:field xpath="@name" />
                    <xs:field xpath="@entity_column" />
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="class" type="classType" use="required" />
        <xs:attribute name="group" type="xs:string" use="required" />
    </xs:complexType>

    <xs:simpleType name="classType">
        <xs:annotation>
            <xs:documentation>
                Class name can contain only [a-zA-Z\].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z\\]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="subscriptionsType">
        <xs:annotation>
            <xs:documentation>
                Subscriptions declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="table" type="subscriptionsTableType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="subscriptionsTableType">
        <xs:annotation>
            <xs:documentation>
                Table declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="tableNameType" use="required" />
        <xs:attribute name="entity_column" type="entityColumnType" use="required" />
    </xs:complexType>

    <xs:simpleType name="entityColumnType">
        <xs:annotation>
            <xs:documentation>
                Entity column can contain only [a-z_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z_]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tableNameType">
        <xs:annotation>
            <xs:documentation>
                Table name can contain only [a-z_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z_]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MageTest/magento/src/app/code/Magento/CatalogSearch/etc/mview.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Mview/etc/mview.xsd">
    <view id="catalogsearch_fulltext" class="Magento\CatalogSearch\Model\Indexer\Fulltext" group="indexer">
        <subscriptions>
            <table name="catalog_product_entity" entity_column="entity_id" />
            <table name="catalog_product_entity_int" entity_column="entity_id" />
            <table name="catalog_product_entity_decimal" entity_column="entity_id" />
            <table name="catalog_product_entity_text" entity_column="entity_id" />
            <table name="catalog_product_entity_varchar" entity_column="entity_id" />
            <table name="catalog_product_entity_datetime" entity_column="entity_id" />
            <table name="catalog_product_website" entity_column="product_id" />
            <table name="cataloginventory_stock_item" entity_column="product_id" />
            <table name="catalog_product_bundle_selection" entity_column="parent_product_id" />
            <table name="catalog_product_super_link" entity_column="product_id" />
            <table name="catalog_product_link" entity_column="product_id" />
        </subscriptions>
    </view>
</config>
