=== MageTest/magento/src/lib/internal/Magento/Framework/Module/etc/module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="module" type="moduleDeclaration" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueModuleName">
            <xs:annotation>
                <xs:documentation>
                    Module name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="module"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="moduleDeclaration">
        <xs:annotation>
            <xs:documentation>
                Module declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element minOccurs="0" maxOccurs="1" name="depends" type="moduleDependency">
                <xs:unique name="uniqueDependencyName">
                    <xs:annotation>
                        <xs:documentation>
                            Dependency name must be unique.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath=".//*" />
                    <xs:field xpath="@name" />
                </xs:unique>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="sequence" type="moduleSequence">
                <xs:unique name="uniqueSequenceName">
                    <xs:annotation>
                        <xs:documentation>
                            Dependency name must be unique.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath=".//*" />
                    <xs:field xpath="@name" />
                </xs:unique>
            </xs:element>
        </xs:all>
        <xs:attribute name="name" type="moduleName" use="required" />
        <xs:attribute name="schema_version" type="schemaVersion" use="optional" />
        <xs:attribute name="active" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="moduleDependency">
        <xs:annotation>
            <xs:documentation>
                Module dependency root element.
            </xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="unbounded" name="module">
                <xs:complexType>
                    <xs:annotation>
                        <xs:documentation>
                            Module dependency that represents another module.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:attribute name="name" type="moduleName" use="required" />
                    <xs:attribute name="type" type="moduleDependencyType" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="extension" type="extensionElement" />
            <xs:element minOccurs="0" maxOccurs="unbounded" name="choice">
                <xs:complexType>
                    <xs:annotation>
                        <xs:documentation>
                            Element that holds alternative extension dependencies.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:sequence>
                        <xs:element minOccurs="2" maxOccurs="unbounded" name="extension" type="extensionElement" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="moduleSequence">
        <xs:annotation>
            <xs:documentation>
                Module dependency root element.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="unbounded" name="module">
                <xs:complexType>
                    <xs:annotation>
                        <xs:documentation>
                            Module dependency that represents another module.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:attribute name="name" type="moduleName" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="moduleDependencyType">
        <xs:annotation>
            <xs:documentation>
                Module dependency type can only be hard or soft.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(hard|soft)?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="extensionElement">
        <xs:annotation>
            <xs:documentation>
                Module dependency that represents PHP extension.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="minVersion" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:simpleType name="moduleName">
        <xs:annotation>
            <xs:documentation>
                Module name attribute can contain only [A-Za-z0-9_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]+[A-Za-z0-9]{1,}_[A-Z]+[A-Z0-9a-z]{1,}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="schemaVersion">
        <xs:annotation>
            <xs:documentation>
                Schema version attribute can contain only [0-9.].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9.]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MageTest/magento/src/app/code/Magento/Reports/etc/module.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
    <module name="Magento_Reports" schema_version="1.6.0.0.2" active="true">
        <sequence>
            <module name="Magento_Customer"/>
            <module name="Magento_Catalog"/>
            <module name="Magento_Sales"/>
            <module name="Magento_Cms"/>
        </sequence>
        <depends>
            <module name="Magento_Store"/>
            <module name="Magento_Eav"/>
            <module name="Magento_Customer"/>
            <module name="Magento_Catalog"/>
            <module name="Magento_Sales"/>
            <module name="Magento_Cms"/>
            <module name="Magento_Backend"/>
            <module name="Magento_Core"/>
            <module name="Magento_Widget"/>
            <module name="Magento_Log"/>
            <module name="Magento_Wishlist"/>
            <module name="Magento_Review"/>
            <module name="Magento_CatalogInventory"/>
            <module name="Magento_Tax"/>
            <module name="Magento_Downloadable"/>
            <module name="Magento_SalesRule"/>
        </depends>
    </module>
</config>
