=== MageTest/magento/src/dev/tests/unit/testsuite/Magento/Webapi/Model/_files/acl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 /**
 * Structure description for acl.xml ACL resource files.
 *
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="acl">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resources">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="resource" type="aclResource" />
                                    </xs:sequence>
                                </xs:complexType>

                                <xs:unique name="uniqueResourceId">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Attribute ID is unique under all ACL resources
                                        </xs:documentation>
                                    </xs:annotation>
                                    <xs:selector xpath=".//*"/>
                                    <xs:field xpath="@id"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="mapping">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" maxOccurs="unbounded" name="resource" type="aclMapping">
                                <xs:unique name="uniqueMappedResourceId">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Attribute ID is unique under all mapped ACL resources
                                        </xs:documentation>
                                    </xs:annotation>
                                    <xs:selector xpath=".//*"/>
                                    <xs:field xpath="@id"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="aclResource">
        <xs:annotation>
            <xs:documentation>
                ACL Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="resource" type="aclResource" />
        </xs:sequence>

        <xs:attribute name="id" type="typeId" use="required" />
        <xs:attribute name="title" type="typeTitle" use="optional" />
        <xs:attribute name="sortOrder" type="xs:int" use="optional" />
    </xs:complexType>

    <xs:complexType name="aclMapping">
        <xs:annotation>
            <xs:documentation>
                ACL Resource mapping.
            </xs:documentation>
        </xs:annotation>

        <xs:attribute name="id" type="typeId" use="required" />
        <xs:attribute name="parent" type="typeId" use="required" />
    </xs:complexType>

    <xs:simpleType name="typeId">
        <xs:annotation>
            <xs:documentation>
                Item ID attribute can have only [A-Za-z0-9_]/[A-Za-z0-9_]. Minimal length is 3 symbols. Case insensitive.
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_0-9]+/?[A-Za-z_0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typeTitle">
        <xs:annotation>
            <xs:documentation>
                Item title attribute minimal length is 3 symbols
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:minLength value="3" />
            <xs:maxLength value="50" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MageTest/magento/src/app/code/Magento/Newsletter/etc/acl.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Acl/etc/acl.xsd">
    <acl>
        <resources>
            <resource id="Magento_Adminhtml::admin">
                <resource id="Magento_Adminhtml::marketing">
                    <resource id="Magento_Adminhtml::marketing_communications">
                        <resource id="Magento_Newsletter::template" title="Newsletter Template" sortOrder="20" />
                        <resource id="Magento_Newsletter::queue" title="Newsletter Queue" sortOrder="30"/>
                        <resource id="Magento_Newsletter::subscriber" title="Newsletter Subscribers" sortOrder="40"/>
                    </resource>
                </resource>
                <resource id="Magento_Reports::report">
                    <resource id="Magento_Reports::report_marketing">
                        <resource id="Magento_Newsletter::problem" title="Newsletter Problem Reports" sortOrder="40"/>
                    </resource>
                </resource>
                <resource id="Magento_Adminhtml::stores">
                    <resource id="Magento_Adminhtml::stores_settings">
                        <resource id="Magento_Adminhtml::config">
                            <resource id="Magento_Newsletter::newsletter" title="Newsletter Section" />
                        </resource>
                    </resource>
                </resource>
            </resource>
        </resources>
    </acl>
</config>

=== MageTest/magento/src/dev/tests/unit/testsuite/Magento/Framework/Acl/Resource/Config/Converter/_files/valid_acl.xml
<?xml version="1.0"?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../../lib/internal/Magento/Framework/Acl/etc/acl.xsd">
    <acl>
        <resources>
            <!-- commented text -->
            <resource id="Custom_Module::resource_one" title="Resource One Title" sortOrder="10" disabled="true" />
            <resource id="Custom_Module::resource_two" title="Resource Two Title" sortOrder="20" />
            <resource id="Custom_Module::parent_resource" title="Parent Resource Title" sortOrder="50">
                <!-- commented text -->
                <resource id="Custom_Module::child_resource_one" title="Resource Child Title" sortOrder="30">
                    <!-- commented text -->
                    <resource id="Custom_Module::child_resource_two" title="Resource Child Level 2 Title" sortOrder="10" />
                </resource>
            </resource>
        </resources>
    </acl>
</config>
